# Basic
name:               "Tommy bloggt"
description:        "My personal developer blog around PHP and other programming stuff."
timezone:           Europe/Berlin

url:                "//tommy-muehle.github.io"
author:             "Tommy Muehle"
twitter:
  username:         "tommy_muehle"
social:
  links:
    - https://github.com/tommy-muehle
    - https://www.xing.com/profile/Tommy_Muehle

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  #- name:           "About"
  #  href:           "//tommy-muehle.github.io/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
